### PR TITLE
Use CMake 3.12+ PYBIND11_FINDPYTHON

### PR DESCRIPTION
**Pull request by devw4r**
- https://pybind11.readthedocs.io/en/stable/faq.html?highlight=cmake#cmake-doesn-t-detect-the-right-python-version

Not sure if this is the right place to put this.

### CODE REVIEW

**Comment by namreeb** [comment]
Looks fine to me.  @gtker thoughts?

**Comment by devw4r** [comment]
Don't really know why linux build fails, any ideas?

**Comment by gtker** [comment]
I'll try to investigate the Linux issue.

Why is enabling `PYBIND11_FINDPYTHON` necessary? Are the wheels not using the correct Python versions?

**Comment by gtker** [comment]
@devw4r 

It seems like this is a known issue reported in https://github.com/pybind/pybind11/issues/4802, and https://github.com/scikit-build/scikit-build-core/issues/472. 

The problem seems to be that `manylinux` doesn't ship `Development.Embed`. There seems to be three ways to fix this on Linux:

1. Add `AND NOT UNIX` to `${CMAKE_VERSION} VERSION_GREATER "3.12.0"`.
2. Put `find_package(Python3 REQUIRED COMPONENTS Interpreter Development.Module)` inside the CMake version if statement that you added, just before `add_subdirectory(pybind11)`.
3. Update `pybind11` to the commit in [this open pull request](https://github.com/pybind/pybind11/pull/4805).

I'm guessing the changes in this PR are related to Windows, if that's the case I would just add `AND NOT UNIX` to disable it for Apple/Linux since I haven't had any issues finding Python.

**Comment by devw4r** [comment]
This PR was made for Linux, which was resolving 3.10 instead of 3.11.5.

**Comment by gtker** [comment]
How do I verify that the problem has been fixed?

**Comment by devw4r** [comment]
> How do I verify that the problem has been fixed?

Not sure how to test, for me, adding this PR fixed python resolving locally.

Before:
image

After:
Screenshot from 2023-09-17 12-16-46

**Comment by gtker** [comment]
> > How do I verify that the problem has been fixed?
> 
> Not sure how to test, for me, adding this PR fixed python resolving locally.

I'm not sure if that's so much a bug as it's just the CMake scripts having different priorities. For me on Ubuntu 22.04 with `python3`, `python3-dev`, `python3.11`, and `python3.11-dev` packages installed CMake consistently picks the 3.11 version over the default 3.10.

I'm actually unsure of what the intended way of choosing the Python version is, since most ways seem to just be to set the required `Python3_*` variables to the specific version which is a little hacky.

**Pull request closed without merging**
